### ISSUE TITLE
Trace Function in Windows

### ISSUE THREAD

**Issue by theP13RC3** [euphy/polargraph#3]
Trace doesn't appear to be working, as WinVDIG and Quicktime need installs, and there are no listed instructions on how to get it up and running.

**Comment by euphy** [comment]
You're correct that WinVDIG and Quicktime need to be installed. This whole function is very mysterious!

Have added a new page: https://github.com/euphy/polargraph/wiki/Using-the-trace-function and will close this issue. Thanks!

**Comment by theP13RC3** [comment]
Thanks so much for the fast reply! You're the best!
