### ISSUE TITLE
'motorA' was not declared. Error facing while compiling polargraph

### ISSUE THREAD

**Issue by rajupun** [euphy/polargraph#7]
Sir
I'm using ardiuno Uno cnc shield v3 A4988driver and nema17 stepper motor.
Software side.
Ardiuno 1.8.10
Polargraph​
Pic attached
Regards

**Comment by euphy** [comment]
Please attach more information to the project that you're trying to compile.

**Comment by rajupun** [comment]
Sir
I'm using ardiuno Uno cnc shield v3 A4988driver and nema17 stepper motor.
Software side.
Ardiuno 1.8.10
Polargraph​
Pic attached
Regards

**Comment by rajupun** [comment]
![1586807457465105518789](https://user-images.githubusercontent.com/63608472/79155078-37cb9a00-7dee-11ea-9f34-b74abff62609.jpg)

**Comment by rajupun** [comment]
Pic uploaded

**Comment by euphy** [comment]
This code has been modified, I can't support it. This ticket is closed.

**Comment by rajupun** [comment]
I'm using ardiuno Uno cnc shield v3 A4988driver and nema17 stepper motor.
Can you suggest me which software I should use with window 7.
Regards

**Comment by euphy** [comment]
http://www.instructables.com/id/Polargraph-Drawing-Machine/
https://github.com/euphy/polargraph/wiki
https://github.com/euphy/polargraph_server_a1

**Comment by rajupun** [comment]
Dear sir,
My hardware is different from which link you have driven above.
Regards
